# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Cser2021' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Alamofire'

  # Pods for Cser2021

  target 'Cser2021Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cser2021UITests' do
    # Pods for testing
  end

end
